//FUNÇÃO PREENCHE A COMBOBOX DE SUCURSAL DE ACORDO COM O DADO DO REGIONAL
function lerSucursal() {
	var lista_sucursais = {
		"regioes" : [
				{
					"sigla" : "1",
					"sucursais" : [ "", 
									"841-BELÉM MERCADO", 
									"850-BELÉM REDE",
									"838-SÃO LUIS MERCADO", 
									"847-SÃO LUIS REDE",
									"836-BRASÍLIA MERCADO",
									"845-BRASÍLIA REDE", 
									"853-BRASÍLIA CORPORATE",
									"839-CAMPO GRANDE MERCADO",
									"848-CAMPO GRANDE REDE", 
									"837-CUIABÁ MERCADO",
									"846-CUIABÁ REDE",
									"835-GOIÂNIA MERCADO", 
									"844-GOIÂNIA REDE",
									"842-PALMAS MERCADO",
									"851-PALMAS REDE", 
									"840-MANAUS MERCADO",
									"849-MANAUS REDE",
									"854-MANAUS CORPORATE", 
									"852-PORTO VELHO REDE",
									"843-PORTO VELHO MERCADO",
									"907-TOP TIER",
								  ]
				},
				
				{
					"sigla" : "2",
					"sucursais" : [ "",
									/* "311-BELO HORIZONTE - ATENDIMENTO SAUDE", */
									"624-BELO HORIZONTE MERCADO",
									"608-BH LESTE REDE",
									"607-BH SUL REDE",
									"982-CORPORATE BH I",
									"983-CORPORATE BH II",
									"609-GOV. VALADARES REDE",
									"629-GOV. VALADARES MERCADO",
									"612-JUIZ DE FORA REDE",
									"625-DIVINÓPOLIS MERCADO",
									"626-JUIZ DE FORA MERCADO",
								    "610-POÇOS DE CALDAS REDE",
									"627-POÇOS DE CALDAS MERCADO",
								    "611-UBERLÂNDIA REDE",
									"628-UBERLÂNDIA MERCADO",
									"630-IPATINGA MERCADO",
									"631-MONTES CLAROS MERCADO",
									"907-TOP TIER",
								  ]
				},
				{
					"sigla" : "3",
					"sucursais" : [ "",
									"856-FORTALEZA REDE",
									"866-FORTALEZA MERCADO",
									"877-JUAZEIRO DO NORTE MERCADO",
									"855-JUAZEIRO DO NORTE REDE",
									"873-TERESINA MERCADO",
									"857-JOÃO PESSOA REDE",
									"871-JOÃO PESSOA MERCADO",
									"859-MACEIÓ REDE",
									"868-MACEIÓ MERCADO",
									"870-NATAL MERCADO",
									"864-NORDESTE 2 CORPORATE",
									"858-RECIFE REDE",
									"867-RECIFE MERCADO",
									/* "817-SALVADOR - ATENDIMENTO SAUDE", */
									"875-ARACAJÚ MERCADO",
									"860-BAHIA REDE",
									"869-FEIRA DE SANTANA MERCADO	",
									"874-JUAZEIRO MERCADO",
									"863-NORDESTE 1 CORPORATE",
									"861-SALVADOR REDE",
									"865-SALVADOR MERCADO",
									"876-ITABUNA MERCADO",
									"862-VITÓRIA DA CONQUISTA REDE",
									"872-VITÓRIA DA CONQUISTA MERCADO",
									"907-TOP TIER",
									
								  ]
				},
				{
					"sigla" : "4",
					"sucursais" : ["",
									/* "791-CURITIBA-ATENDIMENTO SAUDE", */
									"644-CASCAVEL MERCADO",
									"660-CASCAVEL REDE",
									"639-CURITIBA MERCADO",
									"634-CURITIBA CORPORATE",
									"657-CURITIBA I REDE",
									"658-CURITIBA II REDE",
									"659-LONDRINA REDE",
									"641-MARINGÁ MERCADO",
									"650-PONTA GROSSA MERCADO",
									"645-BLUMENAU MERCADO",
									"643-CHAPECÓ MERCADO",
									"662-CHAPECO REDE",
									"653-FLORIANÓPOLIS MERCADO",
									"661-FLORIANÓPOLIS REDE",
									"648-JOINVILLE MERCADO",
									"663-JOINVILLE REDE",
									"633-JOINVILLE CORPORATE",
									/* "357-JOINVILLE SAUDE", */
									"642-LONDRINA MERCADO",
									"646-ITAJAÍ MERCADO",
									"652-CRICIÚMA MERCADO",
									"907-TOP TIER",
									
								  ]
				},
				{
					"sigla" : "5",
					"sucursais" : ["",
									/* "244-COPACABANA SAUDE", */
									"602-BARRA DA TIJUCA REDE",
									"615-BARRA DA TIJUCA MERCADO",
									/* "370-NUCL CANDELARIA", */
									"605-CENTRAL REDE",
									"616-CENTRO RJ ASSESSORIA MERCADO",
									"621-NOVA IGUAÇU MERCADO",
									"623-VOLTA REDONDA MERCADO",
									"984-CORPORATE RJ CAPITAL",
									"985-CORPORATE RJ INTERIOR",
									"666-FLUMINENSE REDE",
									"601-GUANABARA REDE",
									"600-NITERÓI REDE",
									"622-PETRÓPOLIS MERCADO",
									"604-PRIME RJ REDE",
									"613-RIO DE JANEIRO MERCADO",
									"603-RIO OESTE REDE",
									"606-VITÓRIA REDE",
									"617-VITÓRIA MERCADO",
									"907-TOP TIER",

								  ]
				},
				{
					"sigla" : "6",
					"sucursais" : [ "",
									/* "793-PORTO ALEGRE - ATENDIMENTO  SAÚDE", */
									"636-CAXIAS DO SUL MERCADO",
									"655-CAXIAS DO SUL REDE",
									"649-NOVO HAMBURGO MERCADO",
									"640-PASSO FUNDO MERCADO",
									"635-PORTO ALEGRE MERCADO",
									"654-PORTO ALEGRE REDE",
									"632-PORTO ALEGRE CORPORATE",
									"656-SANTA MARIA REDE",
									"647-BENTO GONÇALVES MERCADO",
									"638-PELOTAS MERCADO",
									"637-SANTA MARIA MERCADO",
									"651-SANTO ÂNGELO MERCADO",
									"907-TOP TIER",
									
								  ]
				},
				{
					"sigla" : "7",
					"sucursais" : [ "",
									/* "768-NC CENTRALIZADORA", */
									"977-CENTRO SP ASSESSORIAS MERCADO",
									"971-GUARULHOS MERCADO",
									"965-INDIANÓPOLIS MERCADO",
									"955-ITAQUERA REDE",
									"959-LAPA REDE",
									"969-LAPA MERCADO",
									"966-NOVA CENTRAL MERCADO",
									"953-NOVA CENTRAL REDE",
									"980-NOVA CENTRAL CORPORATE I",
									"981-NOVA CENTRAL CORPORATE II",
									"958-OSASCO REDE",
									"967-OSASCO MERCADO",
									"954-PAULISTA REDE",
									"973-PENHA MERCADO",
									"961-PINHEIROS REDE",
									"947-PRIME SP CAPITAL REDE",
									"950-ITAIM REDE",
									"948-FARIA LIMA REDE",
									"949-PRIME SP 1 REDE",
									"995-PRIVATE REDE",
									"957-SANTANA REDE",
									"978-SANTANA MERCADO",
									"960-SANTO AMARO REDE",
									"975-SANTO AMARO MERCADO",
									"952-SANTO ANDRÉ REDE",
									"962-SANTO ANDRÉ MERCADO",
									"956-SANTOS REDE",
									"979-SANTOS MERCADO",
									"951-TATUAPÉ REDE",
									"970-TATUAPÉ MERCADO",
									"968-ALPHAVILLE MERCADO",
									"964-IPIRANGA MERCADO",
									"972-MOGI DAS CRUZES MERCADO",
									"963-SÃO BERNARDO MERCADO",
									"974-SÃO MIGUEL MERCADO",
									"907-TOP TIER",
									
								  ]
				},
				{
					"sigla" : "8",
					"sucursais" : [ "",
									"911-CAMPINAS MERCADO",
									"912-CAMPINAS CORPORATE",
									"910-CAMPINAS LESTE / OESTE REDE",
									"915-CAMPINAS SUL / JUNDIAÍ REDE",
									"916-JUNDIAÍ MERCADO",
									"943-SÃO JOSÉ DOS CAMPOS REDE",
									"944-SÃO JOSÉ DOS CAMPOS MERCADO",
									"945-SÃO JOSÉ DOS CAMPOS CORPORATE",
									"927-SOROCABA REDE",
									"928-SOROCABA MERCADO",
									"918-RIBEIRÃO PRETO REDE",
									"919-RIBEIRÃO PRETO MERCADO",
									"920-RIBEIRÃO PRETO CORPORATE",
									"923-SÃO CARLOS MERCADO",
									"986-SÃO CARLOS REDE",
									"935-BAURU REDE",
									"936-BAURU MERCADO",
									"931-PRESIDENTE PRUDENTE REDE",
									"932-PRESIDENTE PRUDENTE MERCADO",
									"939-SÃO JOSÉ DO RIO PRETO REDE",
									"940-SÃO JOSÉ DO RIO PRETO MERCADO",
									"933-ARAÇATUBA MERCADO",
									"934-ADAMANTINA MERCADO",
									"937-MARÍLIA MERCADO",
									"941-FERNANDÓPOLIS MERCADO",
									"921-BARRETOS MERCADO",
									"922-FRANCA MERCADO",
									"924-ARARAQUARA MERCADO",
									"925-RIO CLARO MERCADO",
									"913-AMERICANA MERCADO",
									"930-ITAPETININGA MERCADO",
									"929-PIRACICABA MERCADO",
									"946-TAUBATÉ MERCADO",
									"907-TOP TIER",

								  ]
				},
				


				]
	};

	return lista_sucursais;
}